# Generated by Django 5.0.4 on 2024-04-07 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=7)),
                ('last_name', models.CharField(max_length=7)),
                ('phone_number', models.CharField(max_length=7)),
                ('email', models.EmailField(max_length=7)),
                ('password', models.CharField(max_length=18)),
                ('date', models.DateField(auto_now_add=True)),
                ('role', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('home_adress', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Employee_skills',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('skill_title', models.CharField(max_length=20)),
                ('level_of_education', models.CharField(max_length=60)),
                ('school_name', models.CharField(max_length=40)),
                ('attain_year', models.DateField()),
                ('more_information', models.TextField()),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hrapp.employees')),
            ],
        ),
        migrations.CreateModel(
            name='Leave_Application',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('status', models.CharField(max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField()),
                ('number_of_days', models.IntegerField()),
                ('end_date', models.DateField()),
                ('approved_by', models.CharField(max_length=60)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hrapp.employees')),
            ],
        ),
        migrations.CreateModel(
            name='Next_of_kin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=7)),
                ('last_name', models.CharField(max_length=7)),
                ('relationship', models.CharField(max_length=5)),
                ('phone_number', models.CharField(max_length=7)),
                ('email', models.EmailField(max_length=40)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrapp.employees')),
            ],
        ),
    ]
