# Generated by Django 5.0.4 on 2024-04-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0003_alter_employees_options_alter_employees_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='email',
            field=models.EmailField(max_length=40),
        ),
    ]
