# Generated by Django 5.0.4 on 2024-04-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0004_alter_employees_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='email',
            field=models.EmailField(max_length=40, unique=True),
        ),
    ]
