# Generated by Django 5.0.4 on 2024-04-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0005_alter_employees_age_alter_employees_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
