# Generated by Django 5.0.4 on 2024-04-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0006_alter_employees_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='age',
            field=models.IntegerField(default=2006),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employees',
            name='username',
            field=models.CharField(max_length=60),
        ),
    ]
